# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Natop < Formula
  desc "A small, keyboard-driven NATS JetStream dashboard"
  homepage "https://github.com/alevsk/natop"
  version "0.3.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Alevsk/natop/releases/download/v0.3.1/natop_0.3.1_Darwin_x86_64.tar.gz"
      sha256 "127cdf1447604c2dc37c902038badbf79f9637d1f9e7e41d5ee385dee68c3f4a"

      define_method(:install) do
        bin.install "natop"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Alevsk/natop/releases/download/v0.3.1/natop_0.3.1_Darwin_arm64.tar.gz"
      sha256 "d5a596161a8183ebd1e3c5ec9c6663554602d06b243011b6e62113fa7bb799f4"

      define_method(:install) do
        bin.install "natop"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Alevsk/natop/releases/download/v0.3.1/natop_0.3.1_Linux_x86_64.tar.gz"
      sha256 "52a3fe7e71929cf8e3b373e8e57ae78b4545fab7939cd9883cd3f010d30e3218"
      define_method(:install) do
        bin.install "natop"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Alevsk/natop/releases/download/v0.3.1/natop_0.3.1_Linux_arm64.tar.gz"
      sha256 "f92d0d55c1de9995af233ca782650e9b29c240ebee82cb5f95287a1d22a4e239"
      define_method(:install) do
        bin.install "natop"
      end
    end
  end

  test do
    system "#{bin}/natop --version"
  end
end
