# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Natop < Formula
  desc "A small, keyboard-driven NATS JetStream dashboard"
  homepage "https://github.com/alevsk/natop"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Alevsk/natop/releases/download/v0.2.0/natop_0.2.0_Darwin_x86_64.tar.gz"
      sha256 "41d9c1e292eb0ab441cb77b9cd809148489d5a8fabc94d8c196a689ef17c6c4d"

      define_method(:install) do
        bin.install "natop"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Alevsk/natop/releases/download/v0.2.0/natop_0.2.0_Darwin_arm64.tar.gz"
      sha256 "1895ab3f03113da9d714caeff26f383944969ccddd819d1e097154ad682aca92"

      define_method(:install) do
        bin.install "natop"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Alevsk/natop/releases/download/v0.2.0/natop_0.2.0_Linux_x86_64.tar.gz"
      sha256 "dacbda8a15333ad654c5faddcc19929955b8297814967fe27742537a3b583f2f"
      define_method(:install) do
        bin.install "natop"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Alevsk/natop/releases/download/v0.2.0/natop_0.2.0_Linux_arm64.tar.gz"
      sha256 "89b10f4423791920d7584e400a5a7596a59c66feebbe25a9acfa3ecb5709d0b5"
      define_method(:install) do
        bin.install "natop"
      end
    end
  end

  test do
    system "#{bin}/natop --version"
  end
end
